# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gamemodes/CruiseGameModeData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gamemodes/CruiseGameModeData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Options_pb2 as Options__pb2
import Math_pb2 as Math__pb2
import Gameplay_pb2 as Gameplay__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"gamemodes/CruiseGameModeData.proto\x1a\rOptions.proto\x1a\nMath.proto\x1a\x0eGameplay.proto\"C\n\x14GasStationParameters\x12\x15\n\rpricePerLitre\x18\x01 \x01(\x02\x12\x14\n\x0c\x63\x61rWashPrice\x18\x02 \x01(\x02\"d\n\x11\x43ruiseUserProfile\x12-\n\x15garage_spawn_position\x18\x01 \x01(\x0b\x32\x0e.TransformData\x12 \n\x18last_selected_car_models\x18\x02 \x03(\t\"\xd8\x02\n\x06\x43ruise\x1a(\n\x0eSpecialization\x12\x16\n\rproto_options\x18\x9a\x05 \x01(\x08\x1a\xe4\x01\n\x05State\x1a\x8b\x01\n\x04Game\x12>\n\x18\x65vent_configuration_list\x18\n \x03(\x0b\x32\x1c.Cruise.State.Game.EventList\x1a\x43\n\tEventList\x12\x0c\n\x04path\x18\x01 \x01(\t\x12(\n\rconfiguration\x18\x02 \x01(\x0b\x32\x11.SeasonDefinition\x1aM\n\x07GameCar\x12\x12\n\nsomeNumber\x18\x01 \x01(\x05\x12\x18\n\x10partial_distance\x18\x02 \x01(\x02\x12\x14\n\x0codo_distance\x18\x03 \x01(\x02\x1a=\n\x0bZonePayload\x12.\n\x13\x65vent_configuration\x18\x01 \x01(\x0b\x32\x11.SeasonDefinition\"0\n\x0c\x43ruiseUiData\x12 \n\x18hide_testing_cruise_mode\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamemodes.CruiseGameModeData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GASSTATIONPARAMETERS']._serialized_start=81
  _globals['_GASSTATIONPARAMETERS']._serialized_end=148
  _globals['_CRUISEUSERPROFILE']._serialized_start=150
  _globals['_CRUISEUSERPROFILE']._serialized_end=250
  _globals['_CRUISE']._serialized_start=253
  _globals['_CRUISE']._serialized_end=597
  _globals['_CRUISE_SPECIALIZATION']._serialized_start=263
  _globals['_CRUISE_SPECIALIZATION']._serialized_end=303
  _globals['_CRUISE_STATE']._serialized_start=306
  _globals['_CRUISE_STATE']._serialized_end=534
  _globals['_CRUISE_STATE_GAME']._serialized_start=316
  _globals['_CRUISE_STATE_GAME']._serialized_end=455
  _globals['_CRUISE_STATE_GAME_EVENTLIST']._serialized_start=388
  _globals['_CRUISE_STATE_GAME_EVENTLIST']._serialized_end=455
  _globals['_CRUISE_STATE_GAMECAR']._serialized_start=457
  _globals['_CRUISE_STATE_GAMECAR']._serialized_end=534
  _globals['_CRUISE_ZONEPAYLOAD']._serialized_start=536
  _globals['_CRUISE_ZONEPAYLOAD']._serialized_end=597
  _globals['_CRUISEUIDATA']._serialized_start=599
  _globals['_CRUISEUIDATA']._serialized_end=647
# @@protoc_insertion_point(module_scope)
