# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gamemodes/PaintShopGameModeData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gamemodes/PaintShopGameModeData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Options_pb2 as Options__pb2
import LogicScene_pb2 as LogicScene__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%gamemodes/PaintShopGameModeData.proto\x1a\rOptions.proto\x1a\x10LogicScene.proto\"\x8c\x03\n\tPaintShop\x1a>\n\x0bTeleportCar\x12\x19\n\tcar_pguid\x18\x02 \x01(\x0b\x32\x06.PGUID\x12\x14\n\x0cspawn_number\x18\x01 \x01(\x05\x1a\x0f\n\x05State\x1a\x06\n\x04Game\x1a\x1b\n\x07Message\x1a\x10\n\x0eResetGameState\x1a\xae\x01\n\x0eSpecialization\x12\x16\n\rproto_options\x18\x9a\x05 \x01(\x08\x12\x15\n\rcustomize_car\x18\x01 \x01(\x08\x12\x14\n\x0ckeep_ui_page\x18\x05 \x01(\x08\x12$\n\rshowroom_data\x18\x03 \x01(\x0b\x32\r.ShowroomData\x12\x14\n\x0cis_temporary\x18\x04 \x01(\x08\x12\x15\n\rshowroom_type\x18\x06 \x01(\x05J\x04\x08\x02\x10\x03\x1a`\n\x07\x43ommand\x1a\x17\n\x15SessionInitialization\x1a*\n\x10\x43onnectionLoaded\x12\x16\n\x06\x63\x61r_id\x18\x01 \x01(\x0b\x32\x06.PGUID\x1a\x10\n\x0eRestartSessionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamemodes.PaintShopGameModeData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAINTSHOP']._serialized_start=75
  _globals['_PAINTSHOP']._serialized_end=471
  _globals['_PAINTSHOP_TELEPORTCAR']._serialized_start=88
  _globals['_PAINTSHOP_TELEPORTCAR']._serialized_end=150
  _globals['_PAINTSHOP_STATE']._serialized_start=152
  _globals['_PAINTSHOP_STATE']._serialized_end=167
  _globals['_PAINTSHOP_STATE_GAME']._serialized_start=161
  _globals['_PAINTSHOP_STATE_GAME']._serialized_end=167
  _globals['_PAINTSHOP_MESSAGE']._serialized_start=169
  _globals['_PAINTSHOP_MESSAGE']._serialized_end=196
  _globals['_PAINTSHOP_MESSAGE_RESETGAMESTATE']._serialized_start=180
  _globals['_PAINTSHOP_MESSAGE_RESETGAMESTATE']._serialized_end=196
  _globals['_PAINTSHOP_SPECIALIZATION']._serialized_start=199
  _globals['_PAINTSHOP_SPECIALIZATION']._serialized_end=373
  _globals['_PAINTSHOP_COMMAND']._serialized_start=375
  _globals['_PAINTSHOP_COMMAND']._serialized_end=471
  _globals['_PAINTSHOP_COMMAND_SESSIONINITIALIZATION']._serialized_start=386
  _globals['_PAINTSHOP_COMMAND_SESSIONINITIALIZATION']._serialized_end=409
  _globals['_PAINTSHOP_COMMAND_CONNECTIONLOADED']._serialized_start=411
  _globals['_PAINTSHOP_COMMAND_CONNECTIONLOADED']._serialized_end=453
  _globals['_PAINTSHOP_COMMAND_RESTARTSESSION']._serialized_start=455
  _globals['_PAINTSHOP_COMMAND_RESTARTSESSION']._serialized_end=471
# @@protoc_insertion_point(module_scope)
