# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BackendMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BackendMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42\x61\x63kendMessage.proto\x1a\x19google/protobuf/any.proto\";\n\x16\x42\x61\x63kendMessageToBeSent\x12!\n\x03msg\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"3\n\x0e\x42\x61\x63kendMessage\x12!\n\x03msg\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"/\n\x0c\x42\x61\x63kendError\x12\x1f\n\x05\x65rror\x18\x01 \x01(\x0e\x32\x10.BackendResponse*t\n\x0f\x42\x61\x63kendResponse\x12\x0e\n\nRESPONSEOK\x10\x00\x12\n\n\x06NOUSER\x10\x01\x12\x17\n\x13\x42\x41\x43KENDDISCONNECTED\x10\x02\x12\x19\n\x15SERVER_NOT_REGISTERED\x10\x03\x12\x11\n\rDATABASE_DOWN\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BackendMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKENDRESPONSE']._serialized_start=214
  _globals['_BACKENDRESPONSE']._serialized_end=330
  _globals['_BACKENDMESSAGETOBESENT']._serialized_start=51
  _globals['_BACKENDMESSAGETOBESENT']._serialized_end=110
  _globals['_BACKENDMESSAGE']._serialized_start=112
  _globals['_BACKENDMESSAGE']._serialized_end=163
  _globals['_BACKENDERROR']._serialized_start=165
  _globals['_BACKENDERROR']._serialized_end=212
# @@protoc_insertion_point(module_scope)
