# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DateTime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DateTime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Options_pb2 as Options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x44\x61teTime.proto\x1a\rOptions.proto\"D\n\rTimePointData\x12\x16\n\x0enanosecondsUtc\x18\x01 \x01(\x04\x12\x1b\n\x08timeZone\x18\x02 \x01(\x0e\x32\t.TimeZone\"{\n\x1c\x44\x61ylightSavingTimeTransition\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\x1d\n\x05start\x18\x02 \x01(\x0b\x32\x0e.TimePointData\x12\x1b\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x0e.TimePointData\x12\x11\n\tdstOffset\x18\x04 \x01(\x05\"u\n\x0eTimezoneRegion\x12\x19\n\x06region\x18\x01 \x01(\x0e\x32\t.TimeZone\x12\x11\n\tutcOffset\x18\x02 \x01(\x05\x12\x35\n\x0e\x64stTransitions\x18\x03 \x03(\x0b\x32\x1d.DaylightSavingTimeTransition\"<\n\x18TimezoneRegionCollection\x12 \n\x07regions\x18\x01 \x03(\x0b\x32\x0f.TimezoneRegion\"s\n\x19HumanReadableDateTimeData\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\x12\x0c\n\x04hour\x18\x04 \x01(\x05\x12\x0e\n\x06minute\x18\x05 \x01(\x05\x12\x0e\n\x06second\x18\x06 \x01(\x05*\xb5\x03\n\x08TimeZone\x12\x10\n\x0cTimeZone_UTC\x10\x00\x12\x1c\n\x18TimeZone_LocalSystemTime\x10\x01\x12\x12\n\x0eTimeZone_Italy\x10\x02\x12\x14\n\x10TimeZone_Germany\x10\x03\x12\x14\n\x10TimeZone_Belgium\x10\x04\x12\x19\n\x15TimeZone_Spain_Madrid\x10\x05\x12\x1c\n\x18TimeZone_Spain_Barcelona\x10\x06\x12\x13\n\x0fTimeZone_France\x10\x07\x12\x18\n\x14TimeZone_Netherlands\x10\x08\x12\x1a\n\x16TimeZone_UnitedKingdom\x10\t\x12\x14\n\x10TimeZone_Hungary\x10\n\x12\x14\n\x10TimeZone_Austria\x10\x0b\x12\x1f\n\x1bTimeZone_Australia_Bathurst\x10\x0c\x12\x15\n\x11TimeZone_US_Texas\x10\r\x12\x19\n\x15TimeZone_South_Africa\x10\x0e\x12\"\n\x1eTimeZone_Pacific_North_America\x10\x0f\x12\x12\n\x0eTimeZone_Japan\x10\x10\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DateTime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEZONE']._serialized_start=527
  _globals['_TIMEZONE']._serialized_end=964
  _globals['_TIMEPOINTDATA']._serialized_start=33
  _globals['_TIMEPOINTDATA']._serialized_end=101
  _globals['_DAYLIGHTSAVINGTIMETRANSITION']._serialized_start=103
  _globals['_DAYLIGHTSAVINGTIMETRANSITION']._serialized_end=226
  _globals['_TIMEZONEREGION']._serialized_start=228
  _globals['_TIMEZONEREGION']._serialized_end=345
  _globals['_TIMEZONEREGIONCOLLECTION']._serialized_start=347
  _globals['_TIMEZONEREGIONCOLLECTION']._serialized_end=407
  _globals['_HUMANREADABLEDATETIMEDATA']._serialized_start=409
  _globals['_HUMANREADABLEDATETIMEDATA']._serialized_end=524
# @@protoc_insertion_point(module_scope)
