# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: EvoUiTypes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'EvoUiTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x45voUiTypes.proto\"g\n\x0cUIDriftState\x12\x11\n\tisvisible\x18\x01 \x01(\x08\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0f\n\x07\x63urrent\x18\x03 \x01(\x05\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x12\x12\n\nmultiplier\x18\x05 \x01(\x05\"Y\n\x0bUIDragState\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\t\x12\x0c\n\x04\x62\x65st\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\x05\x12\x10\n\x08reaction\x18\x05 \x01(\x05\"*\n\x0bUIGarageCar\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\"7\n\rUIGarageState\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1a\n\x04\x63\x61rs\x18\x02 \x03(\x0b\x32\x0c.UIGarageCar\"\x1e\n\x0eSelectGameMode\x12\x0c\n\x04mode\x18\x01 \x01(\t\"\x1f\n\x0e\x43hangeCarModel\x12\r\n\x05model\x18\x01 \x01(\t\"\xa6\x02\n\x0bUIMenuState\x12\x12\n\nactiveMenu\x18\x01 \x01(\t\x12\x15\n\ractiveSubMenu\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0e\n\x06origin\x18\x04 \x01(\t\x12&\n\x05store\x18\x05 \x03(\x0b\x32\x17.UIMenuState.StoreEntry\x12\x1a\n\x12is_widget_hovering\x18\x06 \x01(\x08\x12%\n\x1dignore_gameplay_input_actions\x18\x07 \x01(\x08\x12\x13\n\x0bplayer_mode\x18\x08 \x01(\x05\x12 \n\x18override_showcase_camera\x18\t \x01(\x08\x1a,\n\nStoreEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"(\n\x0c\x45voDevUiSave\x12\x18\n\x10\x64\x65scriptor_names\x18\x01 \x03(\t*\x81\x01\n\x0cUIBitsetEnum\x12\x0b\n\x07lock_ui\x10\x00\x12\x13\n\x0fis_reconnecting\x10\x01\x12\x11\n\ris_guest_mode\x10\x02\x12\x0c\n\x08no_intro\x10\x03\x12\r\n\tis_online\x10\x04\x12\x0e\n\nis_sandbox\x10\x05\x12\x0f\n\x0bhas_no_cars\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EvoUiTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UIMENUSTATE_STOREENTRY']._loaded_options = None
  _globals['_UIMENUSTATE_STOREENTRY']._serialized_options = b'8\001'
  _globals['_UIBITSETENUM']._serialized_start=722
  _globals['_UIBITSETENUM']._serialized_end=851
  _globals['_UIDRIFTSTATE']._serialized_start=20
  _globals['_UIDRIFTSTATE']._serialized_end=123
  _globals['_UIDRAGSTATE']._serialized_start=125
  _globals['_UIDRAGSTATE']._serialized_end=214
  _globals['_UIGARAGECAR']._serialized_start=216
  _globals['_UIGARAGECAR']._serialized_end=258
  _globals['_UIGARAGESTATE']._serialized_start=260
  _globals['_UIGARAGESTATE']._serialized_end=315
  _globals['_SELECTGAMEMODE']._serialized_start=317
  _globals['_SELECTGAMEMODE']._serialized_end=347
  _globals['_CHANGECARMODEL']._serialized_start=349
  _globals['_CHANGECARMODEL']._serialized_end=380
  _globals['_UIMENUSTATE']._serialized_start=383
  _globals['_UIMENUSTATE']._serialized_end=677
  _globals['_UIMENUSTATE_STOREENTRY']._serialized_start=633
  _globals['_UIMENUSTATE_STOREENTRY']._serialized_end=677
  _globals['_EVODEVUISAVE']._serialized_start=679
  _globals['_EVODEVUISAVE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
