# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GameplayUI.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'GameplayUI.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10GameplayUI.proto\"S\n\x10SimulationUiData\x12 \n\x18show_investigation_panel\x18\x01 \x01(\x08\x12\x1d\n\x15show_simulation_panel\x18\x02 \x01(\x08\"B\n\x0eTimelineUiData\x12\x1a\n\x12show_timeline_menu\x18\x01 \x01(\x08\x12\x14\n\x0c\x65nable_debug\x18\x02 \x01(\x08\"M\n\x13UINotificationTuple\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.UINotificationValueType\x12\x0e\n\x06values\x18\x02 \x03(\t\"\xa4\x01\n\x0eUINotification\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.UINotificationType\x12$\n\x06tuples\x18\x02 \x03(\x0b\x32\x14.UINotificationTuple\x12\x14\n\x0ctime_to_hide\x18\x03 \x01(\r\x12\x33\n\x16notifications_to_clear\x18\x04 \x03(\x0e\x32\x13.UINotificationType\"X\n\x14ScenePresenterUIData\x12\x18\n\x10show_focused_car\x18\x01 \x01(\x08\x12&\n\x1erecreate_all_particle_emitters\x18\x02 \x01(\x08*\xb8\x03\n\x12UINotificationType\x12\x1e\n\x1aUINotificationType_LevelUp\x10\x00\x12\x1e\n\x1aUINotificationType_BestLap\x10\x01\x12 \n\x1cUINotificationType_Xp_Reward\x10\x02\x12%\n!UINotificationType_Credits_Reward\x10\x03\x12\x1c\n\x18UINotificationType_Debug\x10\x04\x12%\n!UINotificationType_SessionPenalty\x10\x05\x12\'\n#UINotificationType_ConnectionStatus\x10\x06\x12\x1f\n\x1bUINotificationType_TyreWear\x10\x07\x12\"\n\x1eUINotificationType_Rental_Done\x10\x08\x12$\n UINotificationType_Gameplay_Info\x10\t\x12\"\n\x1eUINotificationType_CarSettings\x10\n\x12\x1c\n\x18UINotificationType_Clear\x10\x0b*\xce\x01\n\x17UINotificationValueType\x12#\n\x1fUINotificationValueType_Integer\x10\x00\x12\"\n\x1eUINotificationValueType_String\x10\x01\x12%\n!UINotificationValueType_StringKey\x10\x02\x12 \n\x1cUINotificationValueType_Time\x10\x03\x12!\n\x1dUINotificationValueType_Delta\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GameplayUI_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UINOTIFICATIONTYPE']._serialized_start=510
  _globals['_UINOTIFICATIONTYPE']._serialized_end=950
  _globals['_UINOTIFICATIONVALUETYPE']._serialized_start=953
  _globals['_UINOTIFICATIONVALUETYPE']._serialized_end=1159
  _globals['_SIMULATIONUIDATA']._serialized_start=20
  _globals['_SIMULATIONUIDATA']._serialized_end=103
  _globals['_TIMELINEUIDATA']._serialized_start=105
  _globals['_TIMELINEUIDATA']._serialized_end=171
  _globals['_UINOTIFICATIONTUPLE']._serialized_start=173
  _globals['_UINOTIFICATIONTUPLE']._serialized_end=250
  _globals['_UINOTIFICATION']._serialized_start=253
  _globals['_UINOTIFICATION']._serialized_end=417
  _globals['_SCENEPRESENTERUIDATA']._serialized_start=419
  _globals['_SCENEPRESENTERUIDATA']._serialized_end=507
# @@protoc_insertion_point(module_scope)
