# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Mirrors.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Mirrors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rMirrors.proto\"\xcb\x01\n\rCarMirrorInfo\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.CarMirrorInfo.Type\x12\x0b\n\x03yaw\x18\x06 \x01(\x02\x12\r\n\x05pitch\x18\x07 \x01(\x02\x12\x0b\n\x03\x66ov\x18\x08 \x01(\x02\x12\x0e\n\x06vr_yaw\x18\n \x01(\x02\x12\x10\n\x08vr_pitch\x18\x0b \x01(\x02\x12\x0e\n\x06vr_fov\x18\x0c \x01(\x02\x12\x13\n\x0bis_disabled\x18\r \x01(\x08\"\'\n\x04Type\x12\n\n\x06\x43\x65nter\x10\x00\x12\x08\n\x04Left\x10\x01\x12\t\n\x05Right\x10\x02\"N\n\x0eRearCameraInfo\x12\x0b\n\x03yaw\x18\x02 \x01(\x02\x12\r\n\x05pitch\x18\x03 \x01(\x02\x12\x0b\n\x03\x66ov\x18\x04 \x01(\x02\x12\x13\n\x0bis_disabled\x18\x05 \x01(\x08\"V\n\x0e\x43\x61rMirrorsInfo\x12\x1f\n\x07mirrors\x18\x01 \x03(\x0b\x32\x0e.CarMirrorInfo\x12#\n\nrearCamera\x18\x02 \x01(\x0b\x32\x0f.RearCameraInfo\"k\n\x15VirtualMirrorSettings\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\r\n\x05scale\x18\x02 \x01(\x02\x12\x19\n\x11offset_horizontal\x18\x03 \x01(\x02\x12\x17\n\x0foffset_vertical\x18\x04 \x01(\x02\"\xf1\x01\n\x16\x43\x61rMirrorsUserSettings\x12G\n\x10mapCarMirrorData\x18\x01 \x03(\x0b\x32-.CarMirrorsUserSettings.MapCarMirrorDataEntry\x12\x15\n\rsingleModeFov\x18\x02 \x01(\x02\x12-\n\rvirtualMirror\x18\x03 \x01(\x0b\x32\x16.VirtualMirrorSettings\x1aH\n\x15MapCarMirrorDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.CarMirrorsInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Mirrors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARMIRRORSUSERSETTINGS_MAPCARMIRRORDATAENTRY']._loaded_options = None
  _globals['_CARMIRRORSUSERSETTINGS_MAPCARMIRRORDATAENTRY']._serialized_options = b'8\001'
  _globals['_CARMIRRORINFO']._serialized_start=18
  _globals['_CARMIRRORINFO']._serialized_end=221
  _globals['_CARMIRRORINFO_TYPE']._serialized_start=182
  _globals['_CARMIRRORINFO_TYPE']._serialized_end=221
  _globals['_REARCAMERAINFO']._serialized_start=223
  _globals['_REARCAMERAINFO']._serialized_end=301
  _globals['_CARMIRRORSINFO']._serialized_start=303
  _globals['_CARMIRRORSINFO']._serialized_end=389
  _globals['_VIRTUALMIRRORSETTINGS']._serialized_start=391
  _globals['_VIRTUALMIRRORSETTINGS']._serialized_end=498
  _globals['_CARMIRRORSUSERSETTINGS']._serialized_start=501
  _globals['_CARMIRRORSUSERSETTINGS']._serialized_end=742
  _globals['_CARMIRRORSUSERSETTINGS_MAPCARMIRRORDATAENTRY']._serialized_start=670
  _globals['_CARMIRRORSUSERSETTINGS_MAPCARMIRRORDATAENTRY']._serialized_end=742
# @@protoc_insertion_point(module_scope)
