# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ReplayDebug.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ReplayDebug.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LogicScene_pb2 as LogicScene__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ReplayDebug.proto\x1a\x10LogicScene.proto\"\x1f\n\x0fMatrixFrameData\x12\x0c\n\x04time\x18\x01 \x01(\x02\"\x8d\x01\n\x11ReplayCarStatData\x12\x12\n\x02id\x18\x01 \x01(\x0b\x32\x06.PGUID\x12\x17\n\x0fnumMatrixFrames\x18\x02 \x01(\x05\x12\x15\n\rnumBaseFrames\x18\x04 \x01(\x05\x12\x10\n\x08timeSpan\x18\x05 \x01(\x02\x12\x11\n\ttimeStart\x18\x06 \x01(\x02\x12\x0f\n\x07timeEnd\x18\x07 \x01(\x02\"A\n\x18ReplayCarStatDataDetails\x12%\n\x0bmatrixFrame\x18\x03 \x03(\x0b\x32\x10.MatrixFrameData\"p\n\x0fReplayStatsData\x12#\n\x07\x63\x61rData\x18\x01 \x03(\x0b\x32\x12.ReplayCarStatData\x12\x13\n\x0b\x63urrentTime\x18\x02 \x01(\x02\x12\x10\n\x08timeSpan\x18\x03 \x01(\x02\x12\x11\n\ttimeStart\x18\x04 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReplayDebug_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATRIXFRAMEDATA']._serialized_start=39
  _globals['_MATRIXFRAMEDATA']._serialized_end=70
  _globals['_REPLAYCARSTATDATA']._serialized_start=73
  _globals['_REPLAYCARSTATDATA']._serialized_end=214
  _globals['_REPLAYCARSTATDATADETAILS']._serialized_start=216
  _globals['_REPLAYCARSTATDATADETAILS']._serialized_end=281
  _globals['_REPLAYSTATSDATA']._serialized_start=283
  _globals['_REPLAYSTATSDATA']._serialized_end=395
# @@protoc_insertion_point(module_scope)
