# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UIAudioCommands.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'UIAudioCommands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LogicScene_pb2 as LogicScene__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15UIAudioCommands.proto\x1a\x10LogicScene.proto\"<\n\x18UIAudioRequestAudioEvent\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.AudioGuiEventType\"B\n\x14UIAudioResponseEvent\x12*\n\x08response\x18\x01 \x01(\x0e\x32\x18.UIAudioCommandsResponse\"y\n\x0fUIAudioCommands\x12\x36\n\x13request_audio_event\x18\x01 \x01(\x0b\x32\x19.UIAudioRequestAudioEvent\x12.\n\x0eresponse_event\x18\xe8\x07 \x01(\x0b\x32\x15.UIAudioResponseEvent*d\n\x17UIAudioCommandsResponse\x12\x1e\n\x1aUIAudioCommandsResponse_OK\x10\x00\x12)\n%UIAudioCommandResponse_CRITICAL_ERROR\x10\x64\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UIAudioCommands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UIAUDIOCOMMANDSRESPONSE']._serialized_start=296
  _globals['_UIAUDIOCOMMANDSRESPONSE']._serialized_end=396
  _globals['_UIAUDIOREQUESTAUDIOEVENT']._serialized_start=43
  _globals['_UIAUDIOREQUESTAUDIOEVENT']._serialized_end=103
  _globals['_UIAUDIORESPONSEEVENT']._serialized_start=105
  _globals['_UIAUDIORESPONSEEVENT']._serialized_end=171
  _globals['_UIAUDIOCOMMANDS']._serialized_start=173
  _globals['_UIAUDIOCOMMANDS']._serialized_end=294
# @@protoc_insertion_point(module_scope)
